import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const demoLink = '/mainnet/evm/43114/erc721/0x0540E4EE0C5CdBA347C2f0E011ACF8651bB70Eb9/tokens/8005'

const Home = () => (
  <>
    <Head>
      <title>NFT Viewer</title>
      <meta name="description" content="Generated by an AI and copy/pasted by a human" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <Link href={demoLink}>🫵feel free to start from this link</Link>
    </main>
  </>
)

export default Home
